/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Messages;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in cs.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MESSAGES_RECEIVER_ID = Internal.createIndex(DSL.name("receiver_id"), Messages.MESSAGES, new OrderField[] { Messages.MESSAGES.RECEIVER_ID }, false);
    public static final Index MESSAGES_SENDER_ID = Internal.createIndex(DSL.name("sender_id"), Messages.MESSAGES, new OrderField[] { Messages.MESSAGES.SENDER_ID }, false);
}
