/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Messages;
import db.tables.Users;
import db.tables.records.MessagesRecord;
import db.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in cs.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MessagesRecord> KEY_MESSAGES_PRIMARY = Internal.createUniqueKey(Messages.MESSAGES, DSL.name("KEY_messages_PRIMARY"), new TableField[] { Messages.MESSAGES.ID }, true);
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, DSL.name("KEY_users_PRIMARY"), new TableField[] { Users.USERS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MessagesRecord, UsersRecord> MESSAGES_IBFK_1 = Internal.createForeignKey(Messages.MESSAGES, DSL.name("messages_ibfk_1"), new TableField[] { Messages.MESSAGES.SENDER_ID }, Keys.KEY_USERS_PRIMARY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<MessagesRecord, UsersRecord> MESSAGES_IBFK_2 = Internal.createForeignKey(Messages.MESSAGES, DSL.name("messages_ibfk_2"), new TableField[] { Messages.MESSAGES.RECEIVER_ID }, Keys.KEY_USERS_PRIMARY, new TableField[] { Users.USERS.ID }, true);
}
