/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Messages;
import db.tables.Users;


/**
 * Convenience access to all tables in cs.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>cs.messages</code>.
     */
    public static final Messages MESSAGES = Messages.MESSAGES;

    /**
     * The table <code>cs.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
